apiVersion: v1
kind: Endpoints
metadata:
  name: service-proxmox
  namespace: default
subsets:
  - addresses:
      - ip: <put your proxmox ip address here>
    ports:
      - name: http
        port: 8006
